#!/bin/sh

### BEGIN INIT INFO
# Provides:          wlp-replaceINSTANCESERVERNAME
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop WebSphere Application Server Liberty Profile
### END INIT INFO

WLP_USER="wasadmin"

umask 0022

if [ `id -un` != "$WLP_USER" ]; then
  exec runuser -s /bin/sh -l $WLP_USER -c "umask 022;$0 \"$@\""
fi


export WLP_INSTALL_DIR="/opt/liberty/wlp"


SERVER_NAME="wlp-replaceINSTANCESERVERNAME"
export WLP_SKIP_UMASK=

start_service() {
  OPTIONS=--clean
  AUTH_BIND=
  nohup $AUTH_BIND ${WLP_INSTALL_DIR}/bin/server start $SERVER_NAME $OPTIONS >/dev/null 2>&1
  error_code=$?
  return $error_code
}

stop_service() {
  ${WLP_INSTALL_DIR}/bin/server stop $SERVER_NAME
  error_code=$?
  return $error_code
}

status() {
  ${WLP_INSTALL_DIR}/bin/server status $SERVER_NAME
  error_code=$?
  return $error_code
}

statusQuiet() {
  status >/dev/null 2>&1
}

restart() {
  stop_service
  start_service
}

case "$1" in
  start)
    statusQuiet && exit 0
    start_service
    ;;
  stop)
    statusQuiet || exit 0
    stop_service
    ;;
  status)
    status
    ;;
  restart)
    restart
    ;;
  try-restart)
    statusQuiet || exit 0
    restart
    ;;
  *)
    echo "Usage: /etc/init.d/wlp-replaceINSTANCESERVERNAME {start|stop|restart|try-restart|status}"
    exit 2
    ;;
esac

exit $?
