echo "Change log permissions for activemq"
ssh -q rhdbbdbsalvt1 "sudo chown -R wasadmin:wasusers /opt/ActiveMqPreprodALPHAData/"
ssh -q rhdbbdbsalvt2 "sudo chown -R wasadmin:wasusers /opt/ActiveMqPreprodALPHAData/"
echo "activemq restart:"
ssh -q rhdbbdbsalvt1 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq restart"
ssh -q rhdbbdbsalvt2 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq restart"
echo "activemq status:"
ssh -q rhdbbdbsalvt1 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsalvt2 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsomvt1 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsomvt2 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
