echo "activemq stop:"
ssh -q rhdbbdbsalvt1 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq stop" 
ssh -q rhdbbdbsalvt2 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq stop"
ssh -q rhdbbdbsomvt1 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq stop"
ssh -q rhdbbdbsomvt2 "hostname -f ; sudo /opt/liberty/apache-activemq-5.13.3/bin/activemq stop"
echo "activemq start:"
ssh -q rhdbbdbsalvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
ssh -q rhdbbdbsalvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
ssh -q rhdbbdbsomvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
ssh -q rhdbbdbsomvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
echo "activemq status:"
ssh -q rhdbbdbsalvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsalvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsomvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsomvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
