echo "ACTIVEMQ restart OMEGA only"
echo "Change log permissions for activemq"
ssh -q rhdbbdbsomvt1 "sudo chown -R wasadmin:wasusers /opt/ActiveMqPreprodOmegaData/"
ssh -q rhdbbdbsomvt2 "sudo chown -R wasadmin:wasusers /opt/ActiveMqPreprodOmegaData/"
echo "activemq start:"
ssh -q rhdbbdbsomvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq stop"
ssh -q rhdbbdbsomvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq stop"
ssh -q rhdbbdbsomvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
ssh -q rhdbbdbsomvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq start"
echo "activemq status:"
ssh -q rhdbbdbsomvt1 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
ssh -q rhdbbdbsomvt2 "hostname -f ; /opt/liberty/apache-activemq-5.13.3/bin/activemq status"
