#!/bin/sh
for host in $(cat /home/wasadmin/maintence/scripts/properties/DBB-server-list-PREPROD.txt);
do
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink accountsintegration"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink approvals"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink auth"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink authenticationServer"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink bulkIntegrationServer"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink cardsproxyServer"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink cmabeneficiariesServer"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink contacts"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink cxp"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink dbbCentralAdmin"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink entitlements"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink export"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink gateway"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink health"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink limits"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink payments"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink paymentsIntegrationServer"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink productsummary"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink psd2"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink registry"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink shared"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink springbootadmin"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink transactions"
ssh -q wasadmin@$host "hostname -f; cd /logs/liberty ; unlink transactionsExportServer"
ssh -q wasadmin@$host "hostname -f; ls -la /logs/liberty"
done
echo "script done!"
