ssh -q rhdbbauthgm1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-auth status;
/bin/bash /etc/init.d/wlp-authenticationServer status;
/bin/bash /etc/init.d/wlp-defaultServer status; exit -1";
ssh -q rhdbbauthgm2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-auth status;
/bin/bash /etc/init.d/wlp-authenticationServer status;
/bin/bash /etc/init.d/wlp-defaultServer status; exit -1";
ssh -q rhdbbauthgm3.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-auth status;
/bin/bash /etc/init.d/wlp-authenticationServer status; exit -1";
ssh -q rhdbbauthgm4.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-auth status;
/bin/bash /etc/init.d/wlp-authenticationServer status; exit -1";
ssh -q rhdbbcxpgm1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-cxServer status;
/bin/bash /etc/init.d/wlp-cxp status;
/bin/bash /etc/init.d/wlp-dbbCentralAdmin status; exit -1";
ssh -q rhdbbcxpgm2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-cxServer status;
/bin/bash /etc/init.d/wlp-cxp status;
/bin/bash /etc/init.d/wlp-dbbCentralAdmin status; exit -1";
ssh -q rhdbbcxpgm3.mid.aib.pri "hostname -f; date; 
/bin/bash /etc/init.d/wlp-cxServer status;
/bin/bash /etc/init.d/wlp-cxp status; exit -1";
ssh -q rhdbbcxpgm4.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-cxServer status;
/bin/bash /etc/init.d/wlp-cxp status; exit -1";
ssh -q rhdbbdbsalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-approvals status;
/bin/bash /etc/init.d/wlp-contacts status;
/bin/bash /etc/init.d/wlp-limits status;
/bin/bash /etc/init.d/wlp-payments status;
/bin/bash /etc/init.d/wlp-psd2 status;
/bin/bash /etc/init.d/wlp-shared status;
/bin/bash /etc/init.d/wlp-transactions status; exit -1";
ssh -q rhdbbdbsalvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-approvals status;
/bin/bash /etc/init.d/wlp-contacts status;
/bin/bash /etc/init.d/wlp-limits status;
/bin/bash /etc/init.d/wlp-payments status;
/bin/bash /etc/init.d/wlp-psd2 status;
/bin/bash /etc/init.d/wlp-shared status;
/bin/bash /etc/init.d/wlp-transactions status; exit -1";
ssh -q rhdbbdbsomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-approvals status;
/bin/bash /etc/init.d/wlp-contacts status;
/bin/bash /etc/init.d/wlp-limits status;
/bin/bash /etc/init.d/wlp-payments status;
/bin/bash /etc/init.d/wlp-psd2 status;
/bin/bash /etc/init.d/wlp-shared status;
/bin/bash /etc/init.d/wlp-transactions status; exit -1";
ssh -q rhdbbdbsomvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-approvals status;
/bin/bash /etc/init.d/wlp-contacts status;
/bin/bash /etc/init.d/wlp-limits status;
/bin/bash /etc/init.d/wlp-payments status;
/bin/bash /etc/init.d/wlp-psd2 status;
/bin/bash /etc/init.d/wlp-shared status;
/bin/bash /etc/init.d/wlp-transactions status; exit -1";
ssh -q rhdbbintalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-accountsintegration status;
/bin/bash /etc/init.d/wlp-cardsproxyServer status;
/bin/bash /etc/init.d/wlp-cmabeneficiariesServer status;
/bin/bash /etc/init.d/wlp-customerHoldingServer status;
/bin/bash /etc/init.d/wlp-defaultServer status;
/bin/bash /etc/init.d/wlp-health status;
/bin/bash /etc/init.d/wlp-paymentsIntegrationServer status;
/bin/bash /etc/init.d/wlp-springbootadmin status; exit -1";
ssh -q rhdbbintalvt2.mid.aib.pri "hostname -f; date; status;
/bin/bash /etc/init.d/wlp-accountsintegration status;
/bin/bash /etc/init.d/wlp-cardsproxyServer status;
/bin/bash /etc/init.d/wlp-cmabeneficiariesServer status;
/bin/bash /etc/init.d/wlp-customerHoldingServer status;
/bin/bash /etc/init.d/wlp-paymentsIntegrationServer status; exit -1";
ssh -q rhdbbintomvt2.mid.aib.pri "hostname -f; date; status;
/bin/bash /etc/init.d/wlp-accountsintegration status;
/bin/bash /etc/init.d/wlp-cardsproxyServer status;
/bin/bash /etc/init.d/wlp-cmabeneficiariesServer status;
/bin/bash /etc/init.d/wlp-customerHoldingServer status;
/bin/bash /etc/init.d/wlp-paymentsIntegrationServer status; exit -1";
ssh -q rhdbbintomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-accountsintegration status;
/bin/bash /etc/init.d/wlp-cardsproxyServer status;
/bin/bash /etc/init.d/wlp-cmabeneficiariesServer status;
/bin/bash /etc/init.d/wlp-customerHoldingServer status;
/bin/bash /etc/init.d/wlp-paymentsIntegrationServer status;
/bin/bash /etc/init.d/wlp-springbootadmin status; exit -1";
ssh -q rhdbbpdsalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-productsummary status; exit -1";
ssh -q rhdbbpdsalvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-productsummary status; exit -1";
ssh -q rhdbbpdsomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-productsummary status; exit -1";
ssh -q rhdbbpdsomvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-productsummary status; exit -1";
ssh -q rhdbbentalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-entitlements status; exit -1";
ssh -q rhdbbentalvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-entitlements status; exit -1";
ssh -q rhdbbentomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-entitlements status; exit -1";
ssh -q rhdbbentomvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-entitlements status; exit -1";
ssh -q rhdbbexpalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-export status;
/bin/bash /etc/init.d/wlp-transactionsExport status;
/bin/bash /etc/init.d/wlp-transactionsExportServer status; exit -1";
ssh -q rhdbbexpalvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-transactionsExport status;
/bin/bash /etc/init.d/wlp-transactionsExportServer status; exit -1";
ssh -q rhdbbexpomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-export status;
/bin/bash /etc/init.d/wlp-transactionsExport status;
/bin/bash /etc/init.d/wlp-transactionsExportServer status; exit -1";
ssh -q rhdbbexpomvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-transactionsExport status;
/bin/bash /etc/init.d/wlp-transactionsExportServer status; exit -1";
ssh -q rhdbbetlalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-springbootadmin status; exit -1";
ssh -q rhdbbetlomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-springbootadmin status; exit -1";
ssh -q rhdbbbisalvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-bulkIntegrationServer status; exit -1";
ssh -q rhdbbbisalvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-bulkIntegrationServer status; exit -1";
ssh -q rhdbbbisomvt1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-adminportal status;
/bin/bash /etc/init.d/wlp-bulkIntegrationServer status;
/bin/bash /etc/init.d/wlp-libertyServer status; exit -1";
ssh -q rhdbbbisomvt2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-bulkIntegrationServer status; exit -1";
ssh -q rhdbbzulgm1.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-gateway status;
/bin/bash /etc/init.d/wlp-registry status; exit -1";
ssh -q rhdbbzulgm2.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-gateway status;
/bin/bash /etc/init.d/wlp-registry status; exit -1";
ssh -q rhdbbzulgm3.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-registry status; exit -1";
ssh -q rhdbbzulgm4.mid.aib.pri "hostname -f; date;
/bin/bash /etc/init.d/wlp-registry status; exit -1";
